<a href="https://colab.research.google.com/github/KuriaDan/KuriaIPC1/blob/master/Moringa_Data_Science_Core_W1_Independent_Project_2019_06_Daniel_Kuria_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Defining the Question**

# 1. Defining the Question

### a) Specifying the Data Analytic Question

Financial Inclusion remains one of the main obstacles to economic and human development in Africa. For example, across Kenya, Rwanda, Tanzania, and Uganda only 9.1 million adults (or 13.9% of the adult population) have access to or use a commercial bank account.

Traditionally, access to bank accounts has been regarded as an indicator of financial inclusion. Despite the proliferation of mobile money in Africa and the growth of innovative fintech solutions, banks still play a pivotal role in facilitating access to financial services. Access to bank accounts enables households to save and facilitate payments while also helping businesses build up their credit-worthiness and improve their access to other financial services. Therefore, access to bank accounts is an essential contributor to long-term economic growth.

The research problem is to figure out how we can predict which individuals are most likely to have or use a bank account. Your solution will help provide an indication of the state of financial inclusion in Kenya, Rwanda, Tanzania, and Uganda, while providing insights into some of the key demographic factors that might drive individuals’ financial outcomes.

In [4]:
# Let's first import the libraries we will need
# ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt   # Data visualisation libraries 
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn import model_selection
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
%pylab inline
matplotlib.rcParams['figure.dpi'] = 300
matplotlib.rcParams['figure.figsize'] = (8,6)
#from biokit.viz import corrplot

Populating the interactive namespace from numpy and matplotlib


In [5]:
#loading our dataset
FinDat = pd.read_csv('Financial Dataset - 1.csv')
FinDat.head()

country  year  ...              Level of Educuation                Type of Job
0   Kenya  2018  ...              Secondary education              Self employed
1   Kenya  2018  ...              No formal education       Government Dependent
2   Kenya  2018  ...  Vocational/Specialised training              Self employed
3   Kenya  2018  ...                Primary education  Formally employed Private
4   Kenya  2018  ...                Primary education        Informally employed

[5 rows x 13 columns]

In [6]:
#importing the pandas_profiling to preview the dataset and view the profile report
!pip3 install pandas-profiling
import pandas_profiling as pp
pp.ProfileReport(FinDat)

In [7]:
##previewing the columns
FinDat.columns

Index(['country', 'year', 'uniqueid', 'Has a Bank account', 'Type of Location',
       'Cell Phone Access', 'household_size', 'Respondent Age',
       'gender_of_respondent', 'The relathip with head', 'marital_status',
       'Level of Educuation', 'Type of Job'],
      dtype='object')

# Tidying the Dataset

Identifying the Missing Data

In [8]:
#Counting the number of null values in the dataset
FinDat.isnull().sum()

country                   14
year                       0
uniqueid                   0
Has a Bank account        36
Type of Location          15
Cell Phone Access         11
household_size            28
Respondent Age            34
gender_of_respondent      34
The relathip with head     4
marital_status            32
Level of Educuation       29
Type of Job               30
dtype: int64

dropping the null values

In [0]:
#dropping the null values
Fin = FinDat.dropna()

 More data cleaning procedures

In [0]:
##dropping the uniqueid column as it has a high cardinality
Fin=Fin.drop(columns=['uniqueid'])

In [0]:
# Get names of indexes for which year is greater than 2018
indexNames = Fin[Fin['year'] > 2018 ].index
# Delete these row indexes from dataFrame
Fin.drop(indexNames , inplace=True)

In [12]:
Fin.year.unique()

array([2018, 2016, 2017])

#Exploratory Analysis

Ploting the univariate summaries and recording our observations

In [0]:
#univariate analysis of Household size column
mean = Fin.household_size.mean()
stdh = Fin.household_size.std()
modeh = Fin.household_size.mode()
medianh = Fin.household_size.median()
varh = Fin.household_size.var()


In [14]:
mean
#the average size of households in the four countries is 3.7

3.688560411311054

In [15]:
medianh
#the median size of households in the four countries is 3

3.0

In [16]:
modeh
#the mode of the column is 2

0    2.0
dtype: float64

In [17]:
stdh
#the standard deviation of the size of the households in the four countries is 2.28

2.2812745975350435

In [18]:
varh

5.204213789358675

In [0]:
meana = Fin["Respondent Age"].mean()
stda = Fin['Respondent Age'].std()
modea = Fin['Respondent Age'].mode()
mediana = Fin['Respondent Age'].median()
vara = Fin['Respondent Age'].var()

In [20]:
meana
#the average age of the respondents in the study is 38.8 yrs

38.80706940874036

In [21]:
stda
#the standard deviation of the respondents age is 16.51

16.519904564514412

In [22]:
modea
#the mode of the respondents is 30

0    30.0
dtype: float64

In [23]:
mediana
#the median age of the respondents is 35

35.0

In [24]:
vara
#the variance of the ages is 272.91

272.90724682066417

# Visualisations

In [25]:
#boxplot of the household sizes
plt.figure(dpi=200)
Fin.boxplot(["household_size"])


In [26]:
#boxplot of the respondents age columns
plt.figure(dpi=200)
Fin.boxplot(["Respondent Age"])



In [27]:
#histogram of the respondents ages
#Fin['Respondent Age'].hist()
sns.distplot(Fin['Respondent Age'], kde=True)

In [28]:
#histogram of the size of the households
#Fin['household_size'].hist()
sns.distplot(Fin.household_size, kde=True)

#Bivariate analysis

In [29]:
#using a scatter plot to compare the two variables
#Fin.plot(x='Respondent Age', y='household_size', kind='scatter')
plt.figure(dpi=200)
sns.scatterplot(Fin['Respondent Age'], Fin.household_size)

In [0]:
#comparison of the gender of the respondents
fin1 = Fin.groupby(['gender_of_respondent'])['gender_of_respondent'].count()
fin1

fin1.plot(kind='bar', figsize=(8, 6))
plt.show()

In [31]:
#calculating the correlation between respondent age and household size
Fin['Respondent Age'].corr(Fin.household_size)

#respondent age and size of houshold exhibits weak negative correlation


-0.11967115234154871

In [32]:
!pip3 install biokit

     |████████████████████████████████| 204kB 4.9MB/s 
     |████████████████████████████████| 61kB 20.7MB/s 
     |████████████████████████████████| 215kB 42.9MB/s 
     |████████████████████████████████| 2.2MB 41.4MB/s 
     |████████████████████████████████| 3.2MB 33.3MB/s 
     |████████████████████████████████| 153kB 40.1MB/s 
  Created wheel for biokit: filename=biokit-0.4.4-cp36-none-any.whl size=212621 sha256=3bfbe835cde534f44316e81fb60f1b7c0a9535a4ada8b0b259dea14844780e79
  Stored in directory: /root/.cache/pip/wheels/48/e4/9e/7eca6f96742d7eee090aa8d5222026413702df9511f7894125
  Created wheel for easydev: filename=easydev-0.9.37-cp36-none-any.whl size=72197 sha256=7c381dece025de4eab074c5244e4ae2bc2e6d8f26f88f12f91efe3cf84ab189b
  Stored in directory: /root/.cache/pip/wheels/cc/c3/50/d1813a2661a77281137a27ab2e03ae13dee2c7887b984461b4
  Created wheel for bioservices: filename=bioservices-1.6.0-cp36-none-any.whl size=219218 sha256=8f2a7d62341c153425c4ea664aec85d676a1f7094a6566f5c

In [33]:
x.corr(method='pearson', min_periods=1)

NameError: ignored

#Multivariate Analysis

In [0]:
x.corr(method='pearson', min_periods=1)

In [0]:
c = corrplot.Corrplot(x)

In [0]:
#plt.figure(dpi=300)
c.plot(colorbar=False, method='square', shrink=.9 ,rotation=90)

In [0]:
#!pip3 install researchpy
import researchpy as rp
rp.summary_cont(x)

In [0]:
sns.pairplot(x)

##Principal Component Analysis 

In [0]:
#before performing PCA, we have to create dummy variables of the categorical variables
#but first we have to divide the dataset into a feature set and the corresponding labels
x = Fin.drop('Has a Bank account', 1)
y = Fin['Has a Bank account']

In [35]:
#previewing the two new dataframes
x.head()

country  year  ...              Level of Educuation                Type of Job
0   Kenya  2018  ...              Secondary education              Self employed
1   Kenya  2018  ...              No formal education       Government Dependent
2   Kenya  2018  ...  Vocational/Specialised training              Self employed
3   Kenya  2018  ...                Primary education  Formally employed Private
4   Kenya  2018  ...                Primary education        Informally employed

[5 rows x 11 columns]

In [0]:
y.head()

In [0]:
#creating dummy variables for the categorical variables
x = pd.get_dummies(x)


In [0]:
pp.ProfileReport(x)

In [37]:
#previewing the new dataset
x.head()

year  ...  Type of Job_Self employed
0  2018  ...                          1
1  2018  ...                          0
2  2018  ...                          1
3  2018  ...                          0
4  2018  ...                          0

[5 rows x 41 columns]

In [0]:
x.columns

In [0]:
# The next preprocessing step is to divide data into training and test sets. 
# We execute the following script to do so:
#
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [0]:
# Using standard scalar normalization to normalize our feature set. 
# To do this, we execute the following code:
# 
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [0]:
#performing PCA accounting for 95% variance
from sklearn.decomposition import PCA

pca = PCA(.95)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

In [77]:
# Step 7: Explained Variance Ratio
# The PCA class contains explained_variance_ratio_ which returns the variance caused by each of the principal components. 
# We execute the following line of code to find the "explained variance ratio".
# 
explained_variance = pca.explained_variance_ratio_
explained_variance


array([0.10171163, 0.07253785, 0.06972458, 0.06247519, 0.05166259,
       0.04624466, 0.04015419, 0.03564433, 0.03487714, 0.03116651,
       0.02975091, 0.02710112, 0.02627195, 0.02523953, 0.02503204,
       0.02476803, 0.02467043, 0.024296  , 0.02415896, 0.02392125,
       0.02372821, 0.02327924, 0.02208826, 0.02111412, 0.01971555,
       0.01924303, 0.01542758, 0.01323842])

In [78]:
# Step 9: Training and Making Predictions
# In this case we'll use random forest classification for making the predictions.
# 
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)
y_pred

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [79]:
# Step 10: Performance Evaluation
# 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
a = accuracy_score(y_test, y_pred)
print(cm)
print('Accuracy', a)

[[4027    9]
 [ 573   59]]
Accuracy 0.8753213367609255


In [0]:
#

However, after performing PCA, the model is not able to correctly predict for people who will not or don't have bank accounts.
therefore, we will try using LDA

In [80]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
ld1 = LDA(n_components=23)
x_train = ld1.fit_transform(x_train, y_train)
x_test = ld1.transform(x_test)
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

c1 = confusion_matrix(y_test, y_pred)
print(c1)
print('Accuracy', str(accuracy_score(y_test, y_pred)))

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(28, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[[3992   44]
 [ 479  153]]
Accuracy 0.8879605826906598


The model is now able to predict for correct Nos. However the ratio is still heavily skewed towards Yes Yes'


#Multiple regression Analysis

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt   # Data visualisation libraries 
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn import model_selection
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

In [50]:
#Y=Fin['Has a Bank account']
len(Y)

23340

In [51]:
len(x)

23340

In [54]:
Fin.head()

country  year  ...                Type of Job bank
0   Kenya  2018  ...              Self employed    1
1   Kenya  2018  ...       Government Dependent    0
2   Kenya  2018  ...              Self employed    1
3   Kenya  2018  ...  Formally employed Private    0
4   Kenya  2018  ...        Informally employed    0

[5 rows x 13 columns]

In [42]:
x.head()

year  ...  Type of Job_Self employed
0  2018  ...                          1
1  2018  ...                          0
2  2018  ...                          1
3  2018  ...                          0
4  2018  ...                          0

[5 rows x 41 columns]

In [0]:
#Binary encoding our target variable
Fin['bank']=Fin['Has a Bank account'].map({'Yes':1, 'No':0})
Y=Fin[['bank', 'Has a Bank account']]


In [0]:
Y = Y.bank

In [0]:
Y = Y.astype(float)

In [72]:
Y.head()

0    1.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: bank, dtype: float64

In [73]:
x_train, x_test, Y_train, Y_test = train_test_split(x, Y, test_size = 0.4, random_state = 101)
lm = LinearRegression()
results = lm.fit(x_train,Y_train)
predictions = lm.predict(x_test)
plt.scatter(Y_test,predictions)
r2_score(Y_test, predictions) 
(lm.coef_, lm.intercept_)


x2 = sm.add_constant(x.values)  
model = sm.OLS(Y, x2).fit()  
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                   bank   R-squared:                       0.264
Model:                            OLS   Adj. R-squared:                  0.263
Method:                 Least Squares   F-statistic:                     261.3
Date:                Tue, 13 Aug 2019   Prob (F-statistic):               0.00
Time:                        05:21:46   Log-Likelihood:                -4920.3
No. Observations:               23340   AIC:                             9907.
Df Residuals:                   23307   BIC:                         1.017e+04
Df Model:                          32                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         1.5e-05   4.02e-06      3.730      0.0